### ISSUE TITLE
Server status keeps saying "online"

### ISSUE THREAD

**Issue by dzbanke** [leonardosnt/mc-player-counter#2]
When i turn my server down, status on the website keeps saying it's online, and show number of players as 0. When server is turned on, it shows the server is online and number of players online correctly.
I assume this doesn't work anymore or I am just an idiot.
What should I do more with it? I copy-pasted everything and just put my server IP in, didn't change anything.

**Comment by leonardosnt** [comment]
I assume it's because the https://docs.gameapis.net/docs/mc/query caches the query... Maybe you need to wait the cache to become stale (and update).
