### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Heriptik** [leonardosnt/mc-player-counter#4]
Hello, this api don't work

**Comment by Heriptik** [comment]
https://use.gameapis.net/

Shutting down

**Comment by iGPLTV** [comment]
Hello, the API this is using has been shutdown. This will no longer work, sorry.

**Comment by ChineseMarc** [comment]
I have fix for this

**Comment by Bluscream** [comment]
> 
> 
> I have fix for this

What is fix?

**Comment by ChineseMarc** [comment]
This is fixed mark as closed
