### ISSUE TITLE
adding a port doesn't work

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [leonardosnt/mc-player-counter#8]
Added a port to the IP address, shows 0 players online.
Having no port shows players online.
These are two different servers running from the same IP address, one with a port of 25565 (default) and 25566, the 25566 one will not show any players online, when I know there are players there.

**Comment by leonardosnt** [comment]
Update the script url to this: `https://cdn.jsdelivr.net/gh/leonardosnt/mc-player-counter@1.1.4/dist/mc-player-counter.min.js`

**Comment by nzminecraftDOTcom** [comment]
Sweet, that fixed it.
